
var ameji_punctuation = `{
"space": {"id": "space", "unicode": ["0020"], "type": "punctuation", "files": [["ameji-punctuation", "space_placeholder.png"]], "meaning": ["empty","space"]},
"newline": {
    "id": "newline", 
    "unicode": ["2424"], "type": "punctuation", 
    "files": [["ameji-punctuation", "newline_placeholder.png"]], 
    "meaning": ["newline character has no symbol. It's an empty div. This is just a placeholder"]
    },

"period": {"id": "period", "unicode": ["002E"],"type": "punctuation", "files": [["ameji-punctuation", "period.png"]], "meaning": ["period"]}, 
"comma": {"id": "comma", "unicode": ["002C"], "type": "punctuation", "files": [["ameji-punctuation", "comma.png"]], "meaning": ["comma"]}, 
"colon": {"id": "colon", "unicode": ["003A"], "type": "punctuation", "files": [["ameji-punctuation", "colon.png"]], "meaning": ["colon"]}, 
"semicolon": {"id": "semicolon", "unicode": ["003B"], "type": "punctuation", "files": [["ameji-punctuation", "semicolon.png"]], "meaning": ["semicolon"]}, 
"empty": {"id": "empty", "unicode": ["0020"], "type": "punctuation", "files": [["ameji-punctuation", "empty.png"]], "meaning": ["empty"]},

"equals": {"id": "equals", "unicode": ["003D"], "type": "punctuation", "files": [["ameji-punctuation", "equals.png"]], "meaning": ["equals"]}, 
"dash": {"id": "dash", "unicode": ["002D"], "type": "punctuation", "files": [["ameji-punctuation", "dash.png"]], "meaning": ["dash"]}, 
"slash-backward": {"id": "slash-backward", "unicode": ["005C"], "type": "punctuation", "files": [["ameji-punctuation", "slash-backward.png"]], "meaning": ["slash-backward"]}, 
"slash-forward": {"id": "slash-forward", "unicode": ["002F"], "type": "punctuation", "files": [["ameji-punctuation", "slash-forward.png"]], "meaning": ["slash-forward"]}, 
"double-slash-forward": {"id": "double-slash-forward", "unicode": ["002F","002F"], "type": "punctuation", "files": [["ameji-punctuation", "double-slash-forward.png"]], "meaning": ["double-slash-forward"]}, 
"double-slash-backward": {"id": "double-slash-backward", "unicode": ["005C","005C"], "type": "punctuation", "files": [["ameji-punctuation", "double-slash-backward.png"]], "meaning": ["double-slash-backward"]}, 
"vertical-line": {"id": "vertical-line", "unicode": ["007C"], "type": "punctuation", "files": [["ameji-punctuation", "vertical-line.png"]], "meaning": ["vertical-line"]}, 
"vertical-line-dashed": {"id": "vertical-line-dashed", "unicode": ["250A"], "type": "punctuation", "files": [["ameji-punctuation", "vertical-line-dashed.png"]], "meaning": ["vertical-line-dashed"]}, 
"cross-diagonal": {"id": "cross-diagonal", "unicode": ["2715"], "type": "punctuation", "files": [["ameji-punctuation", "cross-diagonal.png"]], "meaning": ["cross-diagonal"]}, 
"checkmark": {"id": "checkmark", "unicode": ["2713"], "type": "punctuation", "files": [["ameji-punctuation", "checkmark.png"]], "meaning": ["checkmark"]}, 

"bracket-left": {"id": "bracket-left", "unicode": ["0028"], "type": "punctuation", "files": [["ameji-punctuation", "bracket-left.png"]], "meaning": ["bracket-left"]}, 
"bracket-left-with-arrow-down": {"id": "bracket-left-with-arrow-down", "unicode": ["21B3"], "type": "punctuation", "files": [["ameji-punctuation", "bracket-left-with-arrow-down.png"]], "meaning": ["bracket-left-with-arrow-down"]},
"bracket-left-with-arrow-up": {"id": "bracket-left-with-arrow-up", "unicode": ["21B1"], "type": "punctuation", "files": [["ameji-punctuation", "bracket-left-with-arrow-up.png"]], "meaning": ["bracket-left-with-arrow-up"]},
"bracket-right-with-arrow-down": {"id": "bracket-right-with-arrow-down", "unicode": ["21B2"], "type": "punctuation", "files": [["ameji-punctuation", "bracket-right-with-arrow-down.png"]], "meaning": ["bracket-right-with-arrow-down"]},
"bracket-right-with-arrow-up": {"id": "bracket-right-with-arrow-up", "unicode": ["21B0"], "type": "punctuation", "files": [["ameji-punctuation", "bracket-right-with-arrow-up.png"]], "meaning": ["bracket-right-with-arrow-up"]},
"bracket-square-left": {"id": "bracket-square-left", "unicode": ["005B"], "type": "punctuation", "files": [["ameji-punctuation", "bracket-square-left.png"]], "meaning": ["bracket-square-left"]}, 
"bracket-square-right": {"id": "bracket-square-right", "unicode": ["005D"], "type": "punctuation", "files": [["ameji-punctuation", "bracket-square-right.png"]], "meaning": ["bracket-square-right"]}, 
"bracket-right": {"id": "bracket-right", "unicode": ["0029"], "type": "punctuation", "files": [["ameji-punctuation", "bracket-right.png"]], "meaning": ["bracket-right"]}, 

"questionmark-open-left": {"id": "questionmark-open-left", "unicode": ["003F"], "type": "punctuation", "files": [["ameji-punctuation", "questionmark-open-left.png"]], "meaning": ["questionmark-open-left"]}, 
"questionmark-upside-down-open-right": {"id": "questionmark-upside-down-open-right", "unicode": ["003F"], "type": "punctuation", "files": [["ameji-punctuation", "questionmark-upside-down-open-right.png"]], "meaning": ["questionmark-upside-down-open-right"]}, 
"exclamation-mark-thin": {"id": "exclamation-mark-thin", "unicode": ["0021"], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-thin.png"]], "meaning": ["exclamation-mark-thin"]}, 
"exclamation-mark-thin-bracket-left": {"id": "exclamation-mark-thin-bracket-left", "unicode": ["0021","0028"], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-thin-bracket-left.png"]], "meaning": ["exclamation-mark-thin-bracket-left"]}, 
"exclamation-mark-thin-bracket-right": {"id": "exclamation-mark-thin-bracket-right", "unicode": ["0029","0021"], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-thin-bracket-right.png"]], "meaning": ["exclamation-mark-thin-bracket-right"]}, 
"exclamation-mark-thin-upside-down": {"id": "exclamation-mark-thin-upside-down", "unicode": ["00A1"], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-thin-upside-down.png"]], "meaning": ["exclamation-mark-thin-upside-down"]}, 
"exclamation-mark-thin-upside-down-bracket-right": {"id": "exclamation-mark-thin-upside-down-bracket-right", "unicode": ["0029","00A1"], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-thin-upside-down-bracket-right.png"]], "meaning": ["exclamation-mark-thin-upside-down-bracket-right"]}, 
"exclamation-mark-thin-upside-down-bracket-left": {"id": "exclamation-mark-thin-upside-down-bracket-left", "unicode": ["00A1","0028"], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-thin-upside-down-bracket-left.png"]], "meaning": ["exclamation-mark-thin-upside-down-bracket-left"]}, 
"exclamation-mark-hollow": {"id": "exclamation-mark-hollow", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-hollow.png"]], "meaning": ["exclamation-mark-hollow"]}, 
"exclamation-mark-hollow-upside-down": {"id": "exclamation-mark-hollow-upside-down", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-hollow-upside-down.png"]], "meaning": ["exclamation-mark-hollow-upside-down"]}, 
"exclamation-mark-lightbulb-top": {"id": "exclamation-mark-lightbulb-top", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-lightbulb-top.png"]], "meaning": ["exclamation-mark-lightbulb-top"]}, 
"exclamation-mark-lightbulb-top-upside-down": {"id": "exclamation-mark-lightbulb-top-upside-down", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-lightbulb-top-upside-down.png"]], "meaning": ["exclamation-mark-lightbulb-top-upside-down"]}, 
"exclamation-mark-circles": {"id": "exclamation-mark-circles", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-circles.png"]], "meaning": ["exclamation-mark-circles"]}, 
"exclamation-mark-circles-bracket-left": {"id": "exclamation-mark-circles-bracket-left", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-circles-bracket-left.png"]], "meaning": ["exclamation-mark-circles-bracket-left"]}, 
"exclamation-mark-circles-bracket-right": {"id": "exclamation-mark-circles-bracket-right", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-circles-bracket-right.png"]], "meaning": ["exclamation-mark-circles-bracket-right"]}, 
"exclamation-mark-circles-upside-down": {"id": "exclamation-mark-circles-upside-down", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-circles-upside-down.png"]], "meaning": ["exclamation-mark-circles-upside-down"]}, 
"exclamation-mark-circles-upside-down-bracket-right": {"id": "exclamation-mark-circles-upside-down-bracket-right", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-circles-upside-down-bracket-right.png"]], "meaning": ["exclamation-mark-circles-upside-down-bracket-right"]}, 
"exclamation-mark-circles-upside-down-bracket-left": {"id": "exclamation-mark-circles-upside-down-bracket-left", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-circles-upside-down-bracket-left.png"]], "meaning": ["exclamation-mark-circles-upside-down-bracket-left"]}, 
"exclamation-mark": {"id": "exclamation-mark", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark.png"]], "meaning": ["exclamation-mark"]}, 
"exclamation-mark-bracket-left": {"id": "exclamation-mark-bracket-left", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-bracket-left.png"]], "meaning": ["exclamation-mark-bracket-left"]}, 
"exclamation-mark-bracket-right": {"id": "exclamation-mark-bracket-right", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-bracket-right.png"]], "meaning": ["exclamation-mark-bracket-right"]}, 
"exclamation-mark-upside-down": {"id": "exclamation-mark-upside-down", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-upside-down.png"]], "meaning": ["exclamation-mark-upside-down"]}, 
"exclamation-mark-upside-down-bracket-right": {"id": "exclamation-mark-upside-down-bracket-right", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-upside-down-bracket-right.png"]], "meaning": ["exclamation-mark-upside-down-bracket-right"]}, 
"exclamation-mark-upside-down-bracket-left": {"id": "exclamation-mark-upside-down-bracket-left", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "exclamation-mark-upside-down-bracket-left.png"]], "meaning": ["exclamation-mark-upside-down-bracket-left"]}, 
"digit-0": {"id": "digit-0", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-0.png"]], "meaning": ["digit-0"]}, 
"digit-1": {"id": "digit-1", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-1.png"]], "meaning": ["digit-1"]}, 
"digit-2": {"id": "digit-2", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-2.png"]], "meaning": ["digit-2"]}, 
"digit-3": {"id": "digit-3", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-3.png"]], "meaning": ["digit-3"]}, 
"digit-4": {"id": "digit-4", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-4.png"]], "meaning": ["digit-4"]}, 
"digit-5": {"id": "digit-5", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-5.png"]], "meaning": ["digit-5"]}, 
"digit-6": {"id": "digit-6", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-6.png"]], "meaning": ["digit-6"]}, 
"digit-7": {"id": "digit-7", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-7.png"]], "meaning": ["digit-7"]}, 
"digit-8": {"id": "digit-8", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-8.png"]], "meaning": ["digit-8"]}, 
"digit-9": {"id": "digit-9", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "digit-9.png"]], "meaning": ["digit-9"]}, 
"value-relative-posneg-neg4": {"id": "value-relative-posneg-neg4", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-neg4.png"]], "meaning": ["value-relative-posneg-neg4"]}, 
"value-relative-posneg-neg3": {"id": "value-relative-posneg-neg3", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-neg3.png"]], "meaning": ["value-relative-posneg-neg3"]}, 
"value-relative-posneg-neg2": {"id": "value-relative-posneg-neg2", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-neg2.png"]], "meaning": ["value-relative-posneg-neg2"]}, 
"value-relative-posneg-neg1": {"id": "value-relative-posneg-neg1", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-neg1.png"]], "meaning": ["value-relative-posneg-neg1"]}, 
"value-relative-posneg-0": {"id": "value-relative-posneg-0", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-0.png"]], "meaning": ["value-relative-posneg-0"]}, 
"value-relative-posneg-1": {"id": "value-relative-posneg-1", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-1.png"]], "meaning": ["value-relative-posneg-1"]}, 
"value-relative-posneg-2": {"id": "value-relative-posneg-2", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-2.png"]], "meaning": ["value-relative-posneg-2"]}, 
"value-relative-posneg-3": {"id": "value-relative-posneg-3", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-3.png"]], "meaning": ["value-relative-posneg-3"]}, 
"value-relative-posneg-4": {"id": "value-relative-posneg-4", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-posneg-4.png"]], "meaning": ["value-relative-posneg-4"]}, 
"value-relative-0": {"id": "value-relative-0", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-0.png"]], "meaning": ["value-relative-0"]}, 
"value-relative-1": {"id": "value-relative-1", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-1.png"]], "meaning": ["value-relative-1"]}, 
"value-relative-2": {"id": "value-relative-2", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-2.png"]], "meaning": ["value-relative-2"]}, 
"value-relative-3": {"id": "value-relative-3", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-3.png"]], "meaning": ["value-relative-3"]}, 
"value-relative-4": {"id": "value-relative-4", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "value-relative-4.png"]], "meaning": ["value-relative-4"]}, 

"v-left": {"id": "v-left", "unicode": ["003c"], "type": "punctuation", "files": [["ameji-punctuation", "v-left.png"]], "meaning": ["comparision"," ","applied more than"]}, 
"v-right": {"id": "v-right", "unicode": ["003E"], "type": "punctuation", "files": [["ameji-punctuation", "v-right.png"]], "meaning": ["comparision","applied less than","applied more than"]}, 
"v-left-double": {"id": "v-left-double", "unicode": ["226A"], "type": "punctuation", "files": [["ameji-punctuation", "v-left-double.png"]], "meaning": ["superlative"]}, 
"v-right-double": {"id": "v-right-double", "unicode": ["226b"], "type": "punctuation", "files": [["ameji-punctuation", "v-right-double.png"]], "meaning": ["superlative"]}, 
"v-left-triple": {"id": "v-left-triple", "unicode": ["22D8"], "type": "punctuation", "files": [["ameji-punctuation", "v-left-triple.png"]], "meaning": ["too","extreme","overly"]}, 
"v-right-triple": {"id": "v-right-triple", "unicode": ["22D9"], "type": "punctuation", "files": [["ameji-punctuation", "v-right-triple.png"]], "meaning": ["too","extreme","overly"]}, 


"v-up": {"id": "v-up", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "v-up.png"]], "meaning": ["v-up"]}, 
"v-down": {"id": "v-down", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "v-down.png"]], "meaning": ["v-down"]}, 
"arrow-wide-left": {"id": "arrow-wide-left", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "arrow-wide-left.png"]], "meaning": ["arrow-wide-left"]}, 
"arrow-wide-right": {"id": "arrow-wide-right", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "arrow-wide-right.png"]], "meaning": ["arrow-wide-right"]}, 
"arrow-wide-double": {"id": "arrow-wide-double", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "arrow-wide-double.png"]], "meaning": ["arrow-wide-double"]}, 
"arrow-left": {"id": "arrow-left", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "arrow-left.png"]], "meaning": ["arrow-left"]}, 
"arrow-right": {"id": "arrow-right", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "arrow-right.png"]], "meaning": ["arrow-right"]}, 
"unit-temperature-celcius": {"id": "unit-temperature-celcius", "unicode": ["2103"], "type": "punctuation", "files": [["ameji-punctuation", "unit-temperature-celcius.png"]], "meaning": ["unit-temperature-celcius"]}, 
"arrow-double": {"id": "arrow-double", "unicode": [""], "type": "punctuation", "files": [["ameji-punctuation", "arrow-double.png"]], "meaning": ["arrow-double"]}}`